### ISSUE TITLE
Find 3 design inspirations

### ISSUE THREAD

**Issue by quynhtlluu** [Lexyful/What-s-Cookin#1]
Web-Site **(inspiration)

https://dribbble.com/shots/20562544-Travel-website

https://www.canva.com/templates/EAEvGu8duAk-orange-cream-and-white-photographic-food-restaurant-service-website/

https://www.skinnytaste.com/

https://www.justtherecipe.com/

[https://dribbble.com/shots/15666656-Dessert-Recipes-Website?utm_source=Clipboard_Sh[…]tm_content=Dessert%20Recipes%20Website&utm_medium=Social_Share](https://dribbble.com/shots/15666656-Dessert-Recipes-Website?utm_source=Clipboard_Shot&utm_campaign=ozgu&utm_content=Dessert%20Recipes%20Website&utm_medium=Social_Share&utm_source=Clipboard_Shot&utm_campaign=ozgu&utm_content=Dessert%20Recipes%20Website&utm_medium=Social_Share)

[https://dribbble.com/shots/12764792-EasyMeals-Food-Blog-WordPress-Theme?utm_source=[…]%20-%20Food%20Blog%20WordPress%20Theme&utm_medium=Social_Share](https://dribbble.com/shots/12764792-EasyMeals-Food-Blog-WordPress-Theme?utm_source=Clipboard_Shot&utm_campaign=qodeinteractive&utm_content=EasyMeals%20-%20Food%20Blog%20WordPress%20Theme&utm_medium=Social_Share&utm_source=Clipboard_Shot&utm_campaign=qodeinteractive&utm_content=EasyMeals%20-%20Food%20Blog%20WordPress%20Theme&utm_medium=Social_Share))

**Comment by jmartin777** [comment]
Recipe Cards **(inspiration)

https://www.canva.com/p/templates/EAE0isuSXtc-modern-aesthetic-recipe-card/

https://www.canva.com/p/templates/EAFKNy3zh8k-gray-illustrated-simple-recipe-card/

https://www.dreamstime.com/royalty-free-stock-images-vector-retro-recipe-card-layout-convenient-image36752089

**Comment by BriBourassa** [comment]
I am a big fan of the dessert recipe from dribbble!

**Comment by Lexyful** [comment]
that's my vote too!

**Comment by BriBourassa** [comment]
Final decisions: Dessert, Travel, Skinny!
