### ISSUE TITLE
Create README file

### ISSUE THREAD

**Issue by quynhtlluu** [Lexyful/What-s-Cookin#27]

**Comment by quynhtlluu** [comment]
I've typed up much of the README except for Wins and Challenges. We also don't have a demonstration of the app working just yet.

**Comment by Lexyful** [comment]
Lexye's Win- A win for me was that I found that I'm much more comfortable with my class to class interaction. I found it much easier to set up my classes than on the last project. My ability to dig into the console and debug has improved as well.

Lexye's Challenge- We had a hard time splitting the work throughout this challenge. We spent the majority of the time together and that made it hard to accomplish every goal we wanted to.

**Comment by BriBourassa** [comment]
Bri's win - Fetch requests and learning how to use APIs felt like a huge win to me.  Practicing more class-to-class interaction and getting to do more unit tests was also very helpful 

Bri's challenge - getting all the javascript hooked up correctly was a challenge, as was delegating tasks evenly.

**Comment by jmartin777** [comment]
CHALLENGE
Working with three other partners on integrating multiple data models and data manipulation techniques while making sure the code is modular and reusable has been a challenge.Writing tests in proper syntax that cover a variety of happy/path scenarios which test the code has been a great learning curve and added perspective into code architecture of a project. Debugging and fixing any bugs or issues that have arise has been both challenging and rewarding considering the group dynamics / problem-solving as we progress with this project.


WINS
By participating in the development of this application, we were able to gain hands-on experience with new technologies and techniques such as ES6, object and array prototype methods, Fetch API, and Webpack. Our success in implementing a functioning application and data-model has allowed us to enhance our skills in designing user interfaces and visualizing data, as well as ways to improve our abilities in data manipulation and integrating multiple data sources. Our group work on modular reusable code,  network requests and data retrieval has helped us to refine our skills problem-solve in these areas as a group, which is helping to make us collaborative and communicative software developers.
