### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by BriBourassa** [Lexyful/What-s-Cookin#3]

**Comment by BriBourassa** [comment]
https://excalidraw.com/#room=d89dd5b34c28656eb7dd,6F7cT_vq3g0HzyElWcemNw

**Comment by BriBourassa** [comment]
Still need: home button and think about possibilities of nav bar?

**Comment by jmartin777** [comment]
![Image](https://user-images.githubusercontent.com/76410246/216853369-e60ddb76-76fc-4df6-be65-45305cd238e6.png)
