### ISSUE TITLE
Create Recipe class

### ISSUE THREAD

**Issue by quynhtlluu** [Lexyful/What-s-Cookin#5]
- It should have a parameter to take in recipe data.
- It should have methods to determine:

   - A filtered list of recipes based on one or more tags.
   - A filtered list of recipes based on its name or ingredients.

_To calculate the cost of a recipe, you will need to factor in the amount listed in the recipe. The price (`estimatedCostInCents`) of an ingredient is per unit._

_For example, if flour is marked as 100 cents, and the recipe calls for 1.5 cups, then it would cost 150 cents. Similarly, if a tomato is $2, and the recipe requires 2 tomatoes, then the cost would be $4._

**Comment by jmartin777** [comment]
pushed up to Github!
